const {chromium}=require('playwright');(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell'});const p=await b.newPage({viewport:{width:1400,height:900}});const er=[];p.on('pageerror',e=>er.push(e.message));
const ok=(k,v,x='')=>console.log((v?'OK   ':'FAIL ')+k+(x?'  '+x:''));
await p.goto('file://'+process.cwd()+'/local.html');await p.waitForTimeout(2500);
await p.evaluate(async()=>{S.emps[0].rate=33;await saveE();const mk=async(id,name,group,pin,x={})=>{const salt=newSalt();return{id,name,group,salt,hash:await pinHash(salt,pin),...x}};
 __docs['app/users']={items:[await mk('a','Administrator','admin','1234'),await mk('j','Jolanta','kadry','2222',{pay:true}),await mk('w','Wioletta','kadry','3333')]};try{sessionStorage.clear()}catch(e){}await authInit()});
ok('stawka nie trafia do bazy jawnie',await p.evaluate(()=>!JSON.stringify(__docs['app/employees']).includes('"rate"')));
const login=async(id,pin)=>{if(await p.isVisible('#logout'))await p.click('#logout');await p.click(`[data-lgu=${id}]`);await p.fill('#lg-pin',pin);await p.click('#lg-ok');await p.waitForTimeout(400)};
await login('a','1234');await p.click('nav .tab[data-tab=place]');await p.waitForTimeout(300);
await p.fill('#pay-pass','krotkie');await p.click('#pay-unlock');await p.waitForTimeout(300);ok('min. 8 znaków',(await p.textContent('#pay-msg')).includes('8'));
await p.fill('#pay-pass','TajneHaslo2026');await p.click('#pay-unlock');await p.waitForTimeout(1500);
ok('tabela płac',await p.isVisible('[data-pbr]'));
const id=await p.$eval('[data-pbr]',x=>x.dataset.pbr);await p.fill(`[data-prate="${id}"]`,'250');await p.selectOption(`[data-punit="${id}"]`,'d');await p.fill(`[data-pbr="${id}"]`,'7654,32');await p.click('#pay-save');await p.waitForTimeout(800);
const raw=await p.evaluate(()=>JSON.stringify(__docs['app/payroll']));ok('w bazie tylko szyfrogram',!raw.includes('7654')&&!raw.includes('250')&&raw.includes('"ct"'));
await login('w','3333');ok('Wioletta: brak zakładki Płace',await p.evaluate(()=>document.querySelector('nav .tab[data-tab=place]').hidden));
ok('Wioletta: brak stawek w pamięci',await p.evaluate(()=>S.emps.every(e=>e.rate==null)));
ok('Wioletta: brak pól stawki',await p.evaluate(()=>[...document.querySelectorAll('[data-rate]')].every(x=>getComputedStyle(x).display==='none')));
await login('j','2222');await p.click('nav .tab[data-tab=place]');await p.waitForTimeout(500);
await p.fill('#pay-pass','zle-haslo-1');await p.click('#pay-unlock');await p.waitForTimeout(1500);ok('złe hasło',(await p.textContent('#pay-msg')).includes('Błędne'));
await p.fill('#pay-pass','TajneHaslo2026');await p.click('#pay-unlock');await p.waitForTimeout(1500);
ok('Jolanta widzi kwotę',(await p.inputValue(`[data-pbr="${id}"]`))==='7654.32');
await p.click('#pay-approve');await p.waitForTimeout(800);ok('zatwierdzone przez Jolantę',(await p.textContent('#place-body')).includes('zatwierdzony: Jolanta'));
console.log('ERRS',er);await b.close()})();
