const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell'});
const pg=await b.newPage({viewport:{width:1300,height:1000}});const errs=[];pg.on('pageerror',e=>errs.push(e.message));pg.on('console',m=>{if(m.type()==='error'&&!/CERT/.test(m.text()))errs.push('C '+m.text())});
await pg.goto('file://'+process.cwd()+'/local_ai.html');await pg.waitForTimeout(600);
const ok=(k,v,x='')=>console.log((v?'OK   ':'FAIL ')+k+(x?'  '+x:''));
const r=await pg.evaluate(async()=>{const o={};
 o.th=[tripHours('14:30','19:30'),tripHours('14:30','20:45'),tripHours('22:00','02:30'),tripHours('21:00','03:30'),tripHours('x','1'),tripHours('2026-10-07T14:30:00','2026-10-07T21:00:00')];
 o.v=[dutyVerdict(5).dn,dutyVerdict(5.01).dn,dutyVerdict(4.5).dn,dutyVerdict(6.25).text];
 S.abs=[];S.hr={};S.shifts.forEach(s=>{if(['t8','t9','t10','t11'].includes(s.id))s.rest=1});
 const day='2026-10-07';const sc=Object.values(S.scheds).find(s=>s.start<=day&&s.end>=day);S.current=sc.id;
 {const ns=sc.cells.filter(c=>c.date===day&&c.shiftId==='nagel');sc.cells=sc.cells.filter(c=>!(ns.includes(c)&&c!==ns[0]));delete ns[0].locked;ns[0].empId='e7';ns[0].slot=0;}const dutyBefore=sc.cells.find(c=>c.date===day&&c.shiftId==='nagel');o.before=dutyBefore.empId;
 // Roman Wranik = e2
 const idBusy=sc.cells.filter(c=>c.date===day&&c.empId==='e2'&&c.shiftId!=='nagel').map(c=>c.shiftId);o.romanRoutes=idBusy;
 const r1=await HarmonogramPlugin.assignOrder({name:'Wranika',date:day,orders:'Nagel + Perfekt'});o.assign=r1;
 const c=S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel'&&c.empId==='e2')||S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel');o.after={emp:c.empId,orders:c.orders,duty:c.duty,locked:!!c.locked};
 o.dutyCount=S.scheds[sc.id].cells.filter(c=>c.date===day&&c.shiftId==='nagel'&&c.empId).length;
 o.planned=cellDn(c,S.shifts.find(x=>x.id==='nagel'));
 const bad=await HarmonogramPlugin.assignOrder({employeeId:'e99',date:day});o.badEmp=bad.ok;
 const bad2=await HarmonogramPlugin.assignOrder({employeeId:'e2',date:'2030-01-01'});o.noSched=bad2.ok;
 const t1=await HarmonogramPlugin.reportTrip('e2',day,{departure:'14:30',return:'21:00'});o.trip6=t1;
 o.dn6=cellDn(S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel'&&c.empId==='e2'),S.shifts.find(x=>x.id==='nagel'));
 const t2=await HarmonogramPlugin.reportTrip('e2',day,{departure:'14:30',return:'19:30'});o.trip5=t2;
 o.dn5=cellDn(S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel'&&c.empId==='e2'),S.shifts.find(x=>x.id==='nagel'));
 const t3=await HarmonogramPlugin.reportTrip('e2',day,{departure:'22:00',return:'03:00'});o.tripMid=t3;
 const t4=await HarmonogramPlugin.reportTrip('e2',day,{went:false});o.tripNo=t4;o.dn0=cellDn(S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel'&&c.empId==='e2'),S.shifts.find(x=>x.id==='nagel'));
 const t5=await HarmonogramPlugin.reportTrip('e2',day,{departure:'14:30',return:'21:00'});
 // ledger widzi 1 dniówkę
 o.stored=S.scheds[sc.id].cells.find(c=>c.date===day&&c.shiftId==='nagel'&&c.empId==='e2');
 return o});
console.log(JSON.stringify(r));
ok('czas wyjazdu: 5 / 6,25 / 4,5 przez północ / 6,5 / błąd / ISO',JSON.stringify(r.th)==='[5,6.25,4.5,6.5,null,6.5]');
ok('porównanie: 5 h = 0,5, 5,01 h = 1, 4,5 h = 0,5',r.v[0]===0.5&&r.v[1]===1&&r.v[2]===0.5,r.v[3]);
ok('assignOrder: dyżur trafia do Wranika i zastępuje zaplanowany',r.assign.ok&&r.after.emp==='e2'&&r.dutyCount===1,JSON.stringify(r.after));
ok('assignOrder: zlecenia zapisane, status niezrealizowany',JSON.stringify(r.after.orders)==='["Nagel","Perfekt"]'&&!r.after.duty&&r.planned===0);
ok('assignOrder: plan z Założeń (start 14:30, 5 h)',r.assign.planowany.start==='14:30'&&r.assign.planowany.godziny===5&&r.assign.planowany.koniec==='19:30',JSON.stringify(r.assign.planowany));
ok('assignOrder: nieznany kierowca i dzień bez harmonogramu odrzucone',r.badEmp===false&&r.noSched===false);
ok('reportTrip 14:30–21:00 = 6,5 h = 1 dniówka',r.trip6.dniowki===1&&r.trip6.godziny===6.5&&r.dn6===1,r.trip6.porownanie);
ok('reportTrip 14:30–19:30 = 5 h = 0,5 dniówki',r.trip5.dniowki===0.5&&r.dn5===0.5,r.trip5.porownanie);
ok('reportTrip przez północ 22:00–03:00 = 5 h = 0,5',r.tripMid.godziny===5&&r.tripMid.dniowki===0.5);
ok('reportTrip nie wyjechał = 0',r.tripNo.dniowki===0&&r.dn0===0);
ok('zapisano godziny odjazdu i powrotu',r.stored.out==='14:30'&&r.stored.back==='21:00'&&r.stored.dutyH===6.5);
// UI: okno dnia
await pg.evaluate(()=>{renderPlan();openSheet('e2','2026-10-07')});await pg.waitForTimeout(150);
ok('okno dnia ma zlecenia i godziny odjazdu i powrotu',await pg.locator('#duty-orders').count()===1&&await pg.locator('#duty-out').count()===1&&await pg.locator('#duty-back').count()===1);
ok('okno pokazuje plan z Założeń',/Plan z Założeń: start 14:30, 5 h/.test(await pg.locator('#sheet-opts').innerText()));
await pg.fill('#duty-out','14:30');await pg.fill('#duty-back','19:15');
ok('porównanie na żywo: 4,75 h → 0,5',/4,75 h ≤ 5 h, więc 0,5 dniówki/.test(await pg.locator('#duty-cmp').innerText()),await pg.locator('#duty-cmp').innerText());
await pg.fill('#duty-back','20:45');
ok('porównanie na żywo: 6,25 h → 1',/6,25 h > 5 h, więc 1 dniówka/.test(await pg.locator('#duty-cmp').innerText()));
await pg.click('[data-dutysave]');await pg.waitForTimeout(250);
const cs=await pg.evaluate(()=>{const c=Object.values(S.scheds).flatMap(s=>s.cells).find(c=>c.date==='2026-10-07'&&c.shiftId==='nagel'&&c.empId==='e2');return{duty:c.duty,h:c.dutyH,out:c.out,back:c.back,dn:cellDn(c,S.shifts.find(x=>x.id==='nagel')),orders:c.orders}});
ok('zapis z okna: godziny liczone z odjazdu i powrotu',cs.duty==='done'&&cs.h===6.25&&cs.dn===1&&cs.out==='14:30'&&cs.back==='20:45',JSON.stringify(cs));
ok('kafelek pokazuje zlecenia',/Nagel \+ Perfekt/.test(await pg.locator('#plan-table').innerText()));
// postMessage
const pm=await pg.evaluate(()=>new Promise(res=>{const h=ev=>{if(ev.data&&ev.data.action==='orderAssigned'){window.removeEventListener('message',h);res(ev.data)}};window.addEventListener('message',h);window.postMessage({type:'harmonogram',action:'assignOrder',requestId:'r1',employeeId:'e3',date:'2026-10-09',orders:'Perfekt'},'*')}));
ok('postMessage assignOrder odpowiada',pm.requestId==='r1'&&pm.result&&typeof pm.result.ok==='boolean',JSON.stringify(pm.result).slice(0,120));
const pm2=await pg.evaluate(()=>new Promise(res=>{const h=ev=>{if(ev.data&&ev.data.action==='tripReported'){window.removeEventListener('message',h);res(ev.data)}};window.addEventListener('message',h);window.postMessage({type:'harmonogram',action:'reportTrip',requestId:'r2',employeeId:'e3',date:'2026-10-09',departure:'14:30',return:'21:30'},'*')}));
ok('postMessage reportTrip odpowiada (7 h = 1 dniówka)',pm2.requestId==='r2'&&pm2.result.dniowki===1,JSON.stringify(pm2.result));
// asystent
await pg.evaluate(()=>{S.abs=[]});await pg.click('#ai-fab');
const send=async t=>{await pg.fill('#ai-in',t);await pg.click('#ai-send');await pg.waitForFunction(()=>!document.getElementById('ai-send').disabled,null,{timeout:8000});await pg.waitForTimeout(150)};
await send('zlecenie');ok('asystent proponuje zlecenie dodatkowe do zatwierdzenia',await pg.locator('.ai-card.pend').count()===1&&/Nagel \+ Perfekt/.test(await pg.locator('.ai-card.pend').innerText()));
await pg.click('[data-ok]');await pg.waitForTimeout(300);
ok('po zatwierdzeniu dyżur ma zlecenia',await pg.evaluate(()=>{const c=Object.values(S.scheds).flatMap(s=>s.cells).find(c=>c.date==='2026-10-07'&&c.shiftId==='nagel'&&c.empId==='e2');return !!c&&(c.orders||[]).join('+')==='Nagel+Perfekt'&&!c.duty}));
await send('wyjazd');await pg.click('[data-ok]');await pg.waitForTimeout(300);
ok('asystent rozlicza wyjazd 14:30–21:00 jako 1 dniówkę',await pg.evaluate(()=>{const c=Object.values(S.scheds).flatMap(s=>s.cells).find(c=>c.date==='2026-10-07'&&c.shiftId==='nagel'&&c.empId==='e2');return c.duty==='done'&&c.dutyH===6.5&&cellDn(c,S.shifts.find(x=>x.id==='nagel'))===1}));
const tl=await pg.evaluate(()=>HarmonogramAssistant.tools().map(t=>({n:t.name,d:t.description.length,s:JSON.stringify(t.inputSchema).length})));
ok('narzędzia mieszczą się w limitach',tl.length<=16&&tl.every(t=>/^[A-Za-z0-9_-]{1,128}$/.test(t.n)&&t.d<=1024&&t.s<=4096),tl.length+' narzędzi');
await pg.screenshot({path:'trip.png'});
console.log('ERRS',errs);await b.close()})();
